const {chromium}=require('playwright');
const assert=require('node:assert/strict');
const path=require('node:path');
const fs=require('node:fs');
const tmp=fs.mkdtempSync(path.join(require('node:os').tmpdir(),'fcc-v10-'));
const fixturePath=path.join(tmp,'roster.png');
const output=process.env.SCREENSHOT_DIR||tmp;
const base=process.env.BASE_URL||'http://127.0.0.1:5050';
(async()=>{
 const browser=await chromium.launch({...(process.env.BROWSER_CHANNEL?{channel:process.env.BROWSER_CHANNEL}:{}),headless:true});
 const page=await browser.newPage({viewport:{width:1440,height:1000}});const errors=[];page.on('pageerror',e=>errors.push(e.message));
 const fixture=await browser.newPage({viewport:{width:750,height:680}});
 await fixture.setContent(`<html><body style="margin:0;padding:25px;font:24px Arial;background:white;color:#102544"><h2>My fantasy roster</h2>${[['QB','Josh Allen'],['RB','Saquon Barkley'],['WR','Justin Jefferson'],['WR','CeeDee Lamb'],['TE','George Kittle'],['BN','Lamar Jackson']].map(([p,n])=>`<div style="border-top:1px solid #ccc;padding:21px 0"><span style="display:inline-block;width:75px">${p}</span><b>${n}</b></div>`).join('')}</body></html>`);
 await fixture.screenshot({path:fixturePath});await fixture.close();
 let captured=[];
 await page.route('**/api/dashboard?*',async route=>{
  const players=Array.from({length:105},(_,i)=>({name:'Receiver '+i,position:'WR',team:'BUF',rank:i+1,source:'test fixture',photo:''}));
  await route.fulfill({json:{rankings:{WR:players},meta:{season:2026,prior_season:2025,latest_stats_season:2025,stat_seasons:[2026,2025,2024,2023,2022,2021],counts:{WR:105}}}});
 });
 page.on('request',r=>{if(r.url().includes('/api/v10/roster-match'))captured.push(r.postDataJSON())});
 await page.goto(base);await page.locator('#board .playerRow').first().waitFor();assert.equal(await page.locator('#board .playerRow').count(),25);
 await page.locator('[data-pos="WR"]').click();assert.equal(await page.locator('#board .playerRow').count(),100);
 assert.equal(await page.locator('#topStatus').count(),0);assert.equal(await page.getByText('Public site',{exact:true}).count(),0);assert.equal(await page.getByText('Decision Lab',{exact:true}).count(),0);
 await page.locator('.navBtn[data-target="compare"]').click();await page.waitForFunction(()=>document.querySelector('#compareNames').children.length>100,{timeout:120000});
 await page.locator('.navBtn[data-target="league"]').click();await page.locator('#manualOpen').click();await page.locator('#manualSearchResults .catalogRow').first().waitFor({timeout:120000});
 await page.locator('#rosterImage').setInputFiles(fixturePath);
 await page.locator('#applyRosterImage').waitFor({timeout:120000});
 const matches=await page.locator('[data-import-player]').count();assert(matches>=5,`Expected 5+ OCR matches, got ${matches}: ${await page.locator('#rosterText').inputValue()}`);
 assert(captured.length);assert(Object.keys(captured[0]).length===1&&typeof captured[0].text==='string');
 await page.screenshot({path:path.join(output,'v10-roster-import.png'),fullPage:true});
 await page.locator('#applyRosterImage').click();assert((await page.locator('#manualRosterCount').textContent()).includes(String(matches)));
 await page.locator('#manualAnalyze').click();await page.getByText('How to improve this team',{exact:true}).waitFor({timeout:120000});assert((await page.locator('.priorityGrid article').count())>=3);
 await page.getByText('Save across devices & send feedback',{exact:true}).click();await page.locator('#workspaceNew').click();const workspaceKey=await page.locator('#workspaceKey').inputValue();await page.locator('#workspaceSave').click();await page.getByText('Server workspace saved.',{exact:true}).waitFor();
 await page.locator('#workspaceFeedback').fill('V10 browser regression: screenshot roster import and team guidance');await page.locator('#workspaceSend').click();await page.getByText('Feedback recorded:',{exact:false}).waitFor();
 await page.evaluate(()=>window.scrollTo({top:0,behavior:'instant'}));await page.screenshot({path:path.join(output,'v10-team-report.png'),fullPage:true});
 await page.locator('.navBtn[data-target="compare"]').click();await page.waitForFunction(()=>document.querySelector('#compareNames').children.length>100,{timeout:120000});
 await page.locator('#compareA').fill('Josh Allen');await page.locator('#compareB').fill('Lamar Jackson');await page.locator('#compareGo').click();
 await page.locator('.comparePlayer h2').first().waitFor({timeout:150000});assert.equal(await page.locator('.comparePlayer').count(),2);
 await page.locator('[data-view="stats"]').click();await page.locator('#compareSeason').selectOption('2024');await page.locator('#compareContent:not([hidden])').waitFor({timeout:150000});
 assert((await page.locator('#compareStats').textContent()).includes('2024 regular season'));
 await page.evaluate(()=>window.scrollTo({top:0,behavior:'instant'}));await page.screenshot({path:path.join(output,'v10-comparison.png'),fullPage:true});
 await page.setViewportSize({width:390,height:844});await page.locator('.mobileNav [data-target="compare"]').click();
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+2),false);
 await page.screenshot({path:path.join(output,'v10-comparison-mobile.png'),fullPage:true});
 await page.reload();await page.locator('.mobileNav [data-target="league"]').click();await page.locator('#manualOpen').click();await page.waitForFunction(n=>document.querySelector('#manualRosterCount').textContent.includes(String(n)),matches,{timeout:120000});
 await page.request.delete(base+'/api/v9/workspace',{headers:{Authorization:'Bearer '+workspaceKey}});
 assert.deepEqual(errors,[]);await browser.close();for(const name of fs.readdirSync(tmp))fs.unlinkSync(path.join(tmp,name));fs.rmdirSync(tmp);console.log('PASS: real browser OCR, reviewed import, saved roster, real team report, 25/100 ranking views, comparison API/history tabs, workspace and feedback, mobile fit, no JS errors. OCR matched '+matches+' players.');
})().catch(e=>{console.error(e);process.exit(1)});
